//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatech.Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public long Id { get; set; }
        public int IdEmisor { get; set; }
        public int IdReceptor { get; set; }
        public System.DateTime FchEnvio { get; set; }
        public string Mensaje1 { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
