//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatech.Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int Id { get; set; }
        public int IdTipo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public byte[] Imagen { get; set; }
        public string ImagenMimeType { get; set; }
        public int IdOferente { get; set; }
        public Nullable<int> IdDemandante { get; set; }
        public System.DateTime FchPublicacion { get; set; }
        public Nullable<System.DateTime> FchFinalizacion { get; set; }
        public bool Enabled { get; set; }
    
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje> Mensaje { get; set; }
    }
}
